bin\import.cmd json\pre2018\classrooms.json
bin\import.cmd json\pre2018\enrolment-age.json
bin\import.cmd json\pre2018\enrolment-disability.json
bin\import.cmd json\pre2018\enrolment-dropouts.json
bin\import.cmd json\pre2018\enrolment-leavers.json
bin\import.cmd json\pre2018\enrolment-repeaters.json
bin\import.cmd json\pre2018\enrolment.json
bin\import.cmd json\pre2018\entrants-age.json
bin\import.cmd json\pre2018\entrants-education.json
bin\import.cmd json\pre2018\furniture.json
bin\import.cmd json\pre2018\school-positions.json
bin\import.cmd json\pre2018\schools-hierarchy.json
bin\import.cmd json\pre2018\school-infos.json
bin\import.cmd json\pre2018\teacher-attritions.json
bin\import.cmd json\pre2018\teacher-experiences.json
bin\import.cmd json\pre2018\teacher-multilevels.json
bin\import.cmd json\pre2018\textbooks.json
bin\import.cmd json\pre2018\toilets.json
bin\import.cmd json\pre2018\exams-passes.json
bin\import.cmd json\pre2018\exams-scores.json
bin\import.cmd json\pre2018\population.json
bin\import.cmd json\pre2018\school-shifts.json
bin\import.cmd json\pre2018\teacher-educations.json
