bin\import.cmd json\2018\ss-classrooms-qty.json
bin\import.cmd json\2018\ss-disability-qty.json
bin\import.cmd json\2018\ss-dropouts-qty.json
bin\import.cmd json\2018\ss-enrol-qty.json
bin\import.cmd json\2018\ss-entrants-qty.json
bin\import.cmd json\2018\ss-expenses-qty.json
bin\import.cmd json\2018\ss-furniture.json
bin\import.cmd json\2018\ss-orphans-qty.json
bin\import.cmd json\2018\ss-otherRooms.json
bin\import.cmd json\2018\ss-othertlms-qty.json
bin\import.cmd json\2018\ss-repeaters-qty.json
bin\import.cmd json\2018\ss-revenue-qty.json
bin\import.cmd json\2018\ss-school-buildings.json
bin\import.cmd json\2018\ss-school-facilities.json
bin\import.cmd json\2018\ss-school-power.json
bin\import.cmd json\2018\ss-school-shifts.json
bin\import.cmd json\2018\ss-school-teacher-houses.json
bin\import.cmd json\2018\ss-school-water.json
bin\import.cmd json\2018\ss-street-kids-qty.json
bin\import.cmd json\2018\ss-teachers-age-qty.json
bin\import.cmd json\2018\ss-teachers-educ-qty.json
bin\import.cmd json\2018\ss-teachers-exp-qty.json
bin\import.cmd json\2018\ss-teachers-inset-qty.json
bin\import.cmd json\2018\ss-teachers-leave-qty.json
bin\import.cmd json\2018\ss-teachers-multilevel-qty.json
bin\import.cmd json\2018\ss-teachers-skills-qty.json
bin\import.cmd json\2018\ss-teachers-sub-taught-qty.json
bin\import.cmd json\2018\ss-toilets.json
bin\import.cmd json\2018\ss-transin-qty.json
bin\import.cmd json\2018\ss-transout-qty.json
bin\import.cmd json\2018\ss-school-infos.json
bin\import.cmd json\2018\ss-teachers-duties-qty.json
bin\import.cmd json\2018\ss-teacherguides-qty.json
bin\import.cmd json\2018\ss-textbooks-qty.json
bin\import.cmd json\2018\ss-streams-qty.json